### ISSUE TITLE
Cross-section: Geometric shapes

### ISSUE THREAD

**Issue by mwdhont** [jarabroz/Koala#16]
**Is your feature request related to a problem? Please describe.**
Currently, I don't think it's possible to use hollow tubular sections with arbitrary diameter and thickness. When one tries this through FORM3 (https://help.scia.net/17.0/de/pvt/steelcodechecktb/annexes/formcode_3_circular_hollow.htm), SCIA throws you some errors when loading the XML. Probably because only standard sections from the library are supported. These sections from the library are however not sufficient in quite some scenarios.

**Describe the solution you'd like**
I believe it could be very useful to add also the option to add 'Geometric shapes'. As such, a great number of extra flexibility is given to the designer.

**Comment by mwdhont** [comment]
Furthermore, there seems to be a bug when one tries to update the thickness of a section (e.g. 1219/22 -> 1219/25), this does not seem to work neither.

**Comment by jarabroz** [comment]
We are using profile library for steel profiles. The reason is that then you can use steel check in SCIA Engineer without any issue. 
I have checked profile library I found just this profiles for diameter of 1219.
![image](https://user-images.githubusercontent.com/29481431/108504993-0bf32d80-72b7-11eb-842f-44d3faf2dee9.png)
I can add Geometrical profiles to Koala which then can be used with any material. Which types do you want to have?

**Comment by mwdhont** [comment]
Hi Jaroslav,

Thanks for your response. Good to know that the library-profiles have been chosen because of the steel verification. 

Currently, I believe that the hollow tube is the only one we really need. It might be nice to have I-profiles as well to increase the library-independence. 

Enjoy your day,
Michiel

**Comment by mwdhont** [comment]
Hi Jaroslav,

As an additional comment: maybe it's an interesting option to add 'Numerical'-cross-sections as well? This would provide the modeller with a back door in all cases which are currently not covered yet.
